Repository XanaduAI/thewalrus, pull requests merged in 2019-12, with the labels that each got.

#96 Fock gradients
  .circleci/config.yml
  docs/code.rst
  docs/code/fock_gradients.rst
  docs/index.rst
  setup.py
  thewalrus/_hermite_multidimensional.py
  thewalrus/fock_gradients.py
  thewalrus/libwalrus.pyx
  thewalrus/quantum.py
  thewalrus/symplectic.py
  thewalrus/tests/test_fock_gradients.py
  thewalrus/tests/test_quantum.py
Labels: review-ready

#110 Update hermite.rst
  docs/hermite.rst
Labels: merge-ready

#112 Removes unnecesarily big svg's replacing them with rasters in gallery
  docs/gallery/added_circuit.svg
  docs/gallery/cat.ipynb
  docs/gallery/cat.svg
  docs/gallery/cat_circuit.svg
  docs/gallery/cubic.ipynb
  docs/gallery/cubic.svg
  docs/gallery/cubic_circuit.svg
  docs/gallery/fock.ipynb
  docs/gallery/fock.svg
  docs/gallery/fock_circuit.svg
  docs/gallery/four_cat.ipynb
  docs/gallery/four_cat.svg
  docs/gallery/four_cat_circuit.svg
  docs/gallery/kitten.ipynb
  docs/gallery/kitten.png
  docs/gallery/kitten.svg
  docs/gallery/kitten_circuit.svg
  docs/gallery/photon_added.ipynb
  docs/gallery/photon_added.svg
  docs/research.rst
Labels: merge-ready

#115 Move tutorials
  docs/_static/xanadu_gallery.css
  docs/conf.py
  docs/gallery/basics.ipynb
  docs/gallery/gallery.rst
  docs/gallery/haf_benchmark.png
  docs/gallery/haf_benchmark.svg
  docs/gallery/hafnian.png
  docs/gallery/hafnian_tutorial.ipynb
  docs/gallery/perm_benchmark.png
  docs/gallery/perm_benchmark.svg
  docs/gallery/permanent_tutorial.ipynb
  docs/gaussian_states.ipynb
  docs/index.rst
Labels: documentation, review-ready
