Repository XanaduAI/thewalrus, pull requests merged in 2020-03, with the labels that each got.

#144 Remove unnecessary vector from hermite_multidimensional.hpp
  .github/CHANGELOG.md
  include/hermite_multidimensional.hpp
Labels: C++, code quality

#145 Add dask for parallelisation of samples
  .github/CHANGELOG.md
  requirements.txt
  setup.py
  thewalrus/samples.py
  thewalrus/tests/test_samples.py
Labels: python, tests

#147 Docs fixes
  docs/algorithms.rst
  docs/code/csamples.rst
  docs/gallery/cat.ipynb
  docs/gallery/four_cat.ipynb
  docs/gbs.rst
  docs/gbs_sampling.rst
  docs/hafnian.rst
  docs/hermite.rst
  docs/index.rst
  docs/loop_hafnian.rst
  docs/notation.rst
  docs/references.bib
  thewalrus/csamples.py
Labels: WIP, documentation
