Repository XanaduAI/thewalrus, pull requests merged in 2020-05, with the labels that each got.

#166 Hermite and low rank hafnians
  .github/CHANGELOG.md
  docs/algorithms.rst
  docs/hermite.rst
  docs/references.bib
  include/hermite_multidimensional.hpp
  requirements.txt
  setup.py
  thewalrus/__init__.py
  thewalrus/_low_rank_haf.py
  thewalrus/libwalrus.pyx
  thewalrus/quantum.py
  thewalrus/tests/test_low_rank_haf.py
  thewalrus/tests/test_samples.py
Labels: review-ready

#164 clean interface for gates and gradients
  .github/CHANGELOG.md
  thewalrus/fock_gradients.py
  thewalrus/tests/test_fock_gradients.py
Labels: python, review-ready

#173 Fix Numba decorated function docstrings
  .readthedocs.yml
  docs/code/quantum.rst
  docs/conf.py
  docs/requirements.txt
  requirements.txt
  thewalrus/csamples.py
  thewalrus/fock_gradients.py
  thewalrus/samples.py
  thewalrus/symplectic.py
  thewalrus/tests/test_samples_classical.py
Labels: bug, review-ready

#161 Parallelise probabilities
  .github/CHANGELOG.md
  thewalrus/quantum.py
  thewalrus/tests/test_quantum.py
Labels: python, review-ready

#157 Adds a dtype argument to most of the functions in symplectic
  thewalrus/symplectic.py
Labels: python, review-ready
