Repository XanaduAI/thewalrus, pull requests merged in 2020-02, with the labels that each got.

#128 Update hafnian.rst
  docs/hafnian.rst
Labels: documentation

#129 fock_gradients speed improvements
  .github/ACKNOWLEDGMENTS.md
  .github/CHANGELOG.md
  thewalrus/fock_gradients.py
  thewalrus/tests/test_fock_gradients.py
Labels: enhancement, python, review-ready

#130 Update S2gate convention to fit sf
  .github/ACKNOWLEDGMENTS.md
  .github/CHANGELOG.md
  thewalrus/fock_gradients.py
  thewalrus/tests/test_fock_gradients.py
Labels: review-ready

#134 Bug fix in quantum.py density_matrix
  thewalrus/quantum.py
Labels: bug

#136 Fixing threshold clicks
  .github/CHANGELOG.md
  thewalrus/quantum.py
  thewalrus/tests/test_quantum.py
Labels: python, sampling

#137 Covariance matrix of the photon number distribution of a Gaussian state
  .github/CHANGELOG.md
  thewalrus/quantum.py
  thewalrus/tests/test_quantum.py
Labels: enhancement, python, review-ready

#138 Support for python 3.8
  .circleci/config.yml
  .github/CHANGELOG.md
  README.rst
  appveyor.yml
  setup.py
Labels: enhancement
